# Generated by Django 2.2.1 on 2019-05-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190519_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='modif',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
